version: "3"

services:
  fivem:
    build:
      context: ./
      dockerfile: ./dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./server.cfg:/srv/server.cfg
      - ./cache:/srv/cache
    ports:
      - "30120:30120/tcp"
      - "30120:30120/udp"
    depends_on:
      - db

  db:
    image: mariadb
    user: 3000:3000
    environment:
      - MARIADB_ROOT_PASSWORD=rom
      - MARIADB_DATABASE=es_extended
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - fivem
