version: "3"

services:
  fivem:
    build:
      context: ./
      dockerfile: ./dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./server.cfg:/srv/server.cfg
      - ./cache:/srv/cache
    ports:
      - "30120:30120/tcp"
      - "30120:30120/udp"
    depends_on:
      - db

  db:
    image: mariadb
    # user: 3000:3000
    environment:
      - MARIADB_ROOT_PASSWORD=rom
      - MARIADB_DATABASE=es_extended
    volumes:
      - mariadb:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - fivem

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: dbwp
      WORDPRESS_DB_USER: rom
      WORDPRESS_DB_PASSWORD: rom
      WORDPRESS_DB_NAME: fivemdb
    volumes:
      - wordpress:/var/www/html

  dbwp:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: fivemdb
      MYSQL_USER: rom
      MYSQL_PASSWORD: rom
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  mariadb:
