version: "3"

services:
  fivem:
    build:
      context: ./
      dockerfile: ./dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./server.cfg:/srv/server.cfg
      - ./cache:/srv/cache
    ports:
      - "30120:30120/tcp"
      - "30120:30120/udp"

  mariadb:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=roro

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
