name: ci-cd

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy repository via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "."
          target: "/home/romain/workspace/fivem"

  # running:
  #   needs: deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run with docker
  #       uses: appleboy/ssh-action@master
  #       with:
  #         HOST: ${{ secrets.HOST }}
  #         USERNAME: ${{ secrets.USERNAME }}
  #         PORT: ${{ secrets.PORT }}
  #         KEY: ${{ secrets.SSHKEY }}
  #         script: "cd workspace/en.splitviewer.com && sudo chmod +x run.sh && ./run.sh"